### ISSUE TITLE
Dwarf opens DSK and floppy files in the same directory as .jar as read only

### ISSUE THREAD

**Issue by californiaelectric** [devhawala/dwarf#3]
If this behavior can't be changed, then perhaps putting placeholder directories in the dist.zip and adding this detail to the readme will address this.

**Comment by devhawala** [comment]
Hello,

well, learned a new thing about Java: you're right, files in the same directory as the jar-file started as the main program seems to be accessed in R/O mode (tested on Linux). Strange feature of Java...

So as Dwarf cannot not avoid this, i will document this and put some templates into dist.zip.

Regarding your questions/items in the other thread:

- i don't remember where i got globalview from, some "old software" site (WinWorld.com?). Probably all these sites have the same 2.1 package...

- does your working GV disk run the document editor and other tools?  
It would be interesting what is different in this disk compared with the not working disks.

- you mentioned that you have some delevopment tools: are these available somewhere? (my favorite site for this is Bitsavers, which does not have any old mesa development tools for XDE, neither do other sites)

Btw: i'm currently working on a virtual network support for Dwarf, but very close to giving up because not getting further without a working XNS network to see which packets are exchanged between a workstation and a server...

Greetings,
Hans

**Comment by californiaelectric** [comment]
I have a couple of DSK files which run fully and completely under dwarf. It's fantastic - much faster than a whole virtualized environment and I can use arbitrary main window sizes - not limited to old dos/windows support. That's why I was so eager to get Guam and now dwarf to work.

I don't have a clue why some .DSK work and some don't. I may have noticed a pattern that if my gvwin set up in dosbox uses the DSK, then there may be issues. Not 100% confirmed. Running windows 3.1 plus some extras in virtualbox gives me the most stable and best performance but it is very bothersome to move stuff in and out of the virtualized environment and screen size is limited.

Dev tools -Don't have anything beyond XDE for gvwin and the bare minimum needed to put gv into developer mode. I got that stuff from yokwe when I was trying to get Guam to load gvwin last summer.

Contact me at this username at gmail dot com
